MSL: Metal argument buffer use enhancements
KhronosGroup/SPIRV-Cross pull request #1596
Opened 2021-01-18 16:16 UTC by billhollings

Add query for type of MSL texture on desc set bindings:
- When encoding textures to argument buffers, Metal require knowledge of the type of each texture. Querying from shader conversion allows us to use that knowledge when encoding an argument buffer for a specific pipeline.

Support padding between argument buffer struct members to align arguments:

- Metal requires knowledge of the entire argument buffer structure to understand where to populate resources. SPIR-V does not include descriptor set content that is not used by the shader being converted. This makes it impossible for MSL to use a single argument buffer, representing a single descriptor set, across multiple shaders.
- By adding padding between known members of the descriptor set struct, we can define the full positional content of the descriptor-set argument buffer. This allows us to use the same Metal argument buffer across multiple shaders, each of which might only access a small part of the argument buffer.

2021-01-19 11:39 UTC, HansKristian-Work commented
First comment right off the bat. Lots of merge commits in the PR. Please rebase the PR.

2021-01-19 11:41 UTC, HansKristian-Work commented on spirv_msl.hpp
> +	MSLTextureType get_msl_texture_type(uint32_t desc_set, uint32_t binding);
Should probably be const?

2021-01-19 11:42 UTC, HansKristian-Work commented on spirv_msl.cpp
> +   return msl_tex_type;
Formatting.

2021-01-19 11:42 UTC, HansKristian-Work commented on spirv_msl.cpp
> +			msl_tex_type = get_msl_texture_type(get_variable_data_type(var));
Braces for clarity.

2021-01-19 11:43 UTC, HansKristian-Work commented on spirv_msl.hpp
> +enum MSLTextureType
Why is this call useful? It seems like it's a convenience query for apps?

2021-01-19 11:47 UTC, HansKristian-Work commented on spirv_msl.cpp
> +					pad_type.basetype = SPIRType::UInt64;
This is questionable. Doesn't this basically assume that descriptors take up 8 bytes? I would normally expect this kind of interface to specify the descriptor type used for specific IDs.

2021-01-19 11:48 UTC, HansKristian-Work requested changes
Comments.

2021-01-19 11:48 UTC, HansKristian-Work commented on spirv_msl.cpp
> +					pad_type.basetype = SPIRType::UInt64;
AMD texture descriptors are 16 or 32 bytes for example.

2021-01-29 18:46 UTC, billhollings commented
I  pulled the texture type and handled it outside using reflection. Turns out there is also still work to be done on the question of padding. So for now, I'm going to close this PR and resubmit a variation if it turns out to be needed.

2021-01-29 18:46 UTC, closed without merging