MSL: Support long ulong types in buffers in 2.3+.
KhronosGroup/SPIRV-Cross pull request #1642
Opened 2021-03-25 23:42 UTC by mehmetoguzderin

[Metal Shading Language Specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) states that:

> Note: As of Metal 2.3, Metal supports buffers that contain long or ulong data types.

This PR aims to support long and ulong data types in buffers for Metal 2.3+.

2021-03-25 23:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Cross?pullRequest=1642) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Cross?pullRequest=1642) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Cross?pullRequest=1642) it.</sub>

2021-03-26 09:50 UTC, HansKristian-Work commented on spirv_msl.cpp
> +			SPIRV_CROSS_THROW("long types in buffers are only supported in MSL 2.3 and above.");
Need break;

2021-03-26 09:50 UTC, HansKristian-Work commented on spirv_msl.cpp
> +			SPIRV_CROSS_THROW("ulong types in buffers are only supported in MSL 2.3 and above.");
Need break;

2021-03-26 09:50 UTC, HansKristian-Work requested changes
Bugs

2021-03-26 09:57 UTC, mehmetoguzderin commented
@HansKristian-Work wouldn't `break` block execution from visiting `default` case?

2021-03-26 10:42 UTC, HansKristian-Work commented
> @HansKristian-Work wouldn't `break` block execution from visiting `default` case?

It never would, since it falls through to Double. You need to move the Int64/Uint64 checks to the default block.

2021-03-26 12:12 UTC, mehmetoguzderin commented
@HansKristian-Work then we don't add any breaks but throw if type is found to be 64-bit integer _inside_ default case?

2021-03-26 12:23 UTC, mehmetoguzderin commented
I assume break has no impact after throw because that aborts.

2021-03-26 13:34 UTC, mehmetoguzderin commented on spirv_msl.cpp
> +			SPIRV_CROSS_THROW("long types in buffers are only supported in MSL 2.3 and above.");
PTAL at the new commit

2021-03-26 13:34 UTC, mehmetoguzderin commented on spirv_msl.cpp
> +			SPIRV_CROSS_THROW("ulong types in buffers are only supported in MSL 2.3 and above.");
PTAL at the new commit

2021-03-26 17:02 UTC, HansKristian-Work approved these changes

2021-03-26 17:02 UTC, merged