Make repository REUSE compliant and check licenses in CI
KhronosGroup/SPIRV-Cross pull request #1669
Opened 2021-05-08 08:49 UTC by oddhack

Closes #1560

2021-05-08 08:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Cross?pullRequest=1669) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Cross?pullRequest=1669) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Cross?pullRequest=1669) it.</sub>

2021-05-08 10:49 UTC, oddhack commented
> @HansKristian-Work is this repo using Appveyor instead of Github Actions?

Never mind, I discovered a mix of my problems and files ignored by .gitignore which shouldn't have been. All good now.

2021-05-08 11:19 UTC, oddhack commented
@HansKristian-Work from the REUSE perspective this is ready to go, but CI is failing in the Windows step. Possibly I edited some Windows-specific file to add a copyright comment in an illegal way? It's hard to tell from the CI log - it just refers to a group of tests failing - and the deeper log it refers to doesn't seem to be getting saved as a CI artifact, so I'm kinda at a loss to diagnose this.

2021-05-08 14:41 UTC, HansKristian-Work commented on checkout_glslang_spirv_tools.sh
> +GLSLANG_REV=4dcc12d1a441b29d5901bc708bb1343d29d6459f
Why does this change? This causes the CI failure btw.

2021-05-08 14:44 UTC, HansKristian-Work requested changes
Nits.

2021-05-21 09:32 UTC, HansKristian-Work commented
@oddhack Should I just go ahead and clean up the nits?

2021-06-29 09:52 UTC, HansKristian-Work approved these changes
Fixed the nits myself.

2021-06-29 09:52 UTC, merged