Implement set_scalar functions in the specialization constants C API
KhronosGroup/SPIRV-Cross pull request #2123
Opened 2023-03-16 19:12 UTC by skyebird189

This PR adds set_scalar functions for all equivalent get_scalar functions in the specialization constants part of the C API.

I've tested this and it seems to work fine.

2023-03-17 15:17 UTC, HansKristian-Work commented on spirv_cross_c.h
> +SPVC_PUBLIC_API void spvc_constant_set_scalar_i8(spvc_constant constant, unsigned column, unsigned row, int value);
The types are wrong here:
8 -> unsigned and signed char
16 -> unsigned and signed short
FP16 -> unsigned short, it's supposed to be the raw fp16 payload, it gets decoded later in SPIRConstant::scalar_fp16().

2023-03-17 15:18 UTC, HansKristian-Work requested changes
Mostly types being wrong, but otherwise ok to add this.

Also, remember to update SPVC_C_API_VERSION_MINOR and the corresponding value in CMakeLists.txt

2023-03-17 17:51 UTC, skyebird189 commented
I've made the requested changes, and hopefully fixed the types.

2023-03-21 11:18 UTC, HansKristian-Work commented on spirv_cross_c.cpp
> +	constant->m.c[column].r[row].u32 = uint32_t(value);
need to cast to int32_t here, then uint32_t.

2023-03-28 15:49 UTC, skyebird189 commented
I've fixed the f16 type to use a u32, hopefully this is all good now!

2023-03-29 17:23 UTC, HansKristian-Work approved these changes
LGTM when CI passes.

2023-03-29 18:36 UTC, merged