GLSL: Support GL_KHR_shader_subgroup_arithmetic (WIP)
KhronosGroup/SPIRV-Cross pull request #2133
Opened 2023-04-02 15:11 UTC by georgeouzou

Support OpenGL workarounds for subgroup arithmetic group operations.

NVIDIA workarounds are based on  GL_NV_shader_thread_shuffle.
AMD workarounds will be based on GL_AMD_shader_ballot.

2023-04-02 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/SPIRV-Cross?pullRequest=2133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/SPIRV-Cross?pullRequest=2133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/SPIRV-Cross?pullRequest=2133) it.</sub>

2023-04-11 14:28 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +void CompilerGLSL::emit_subgroup_arithmetic_workaround(std::string func, Op op, GroupOperation group_op)
const reference for func seems more appropriate.

2023-04-11 14:28 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +	for (const TypeInfo& t : type_infos) {
Brace on next line. `const TypeInfo &t`.

2023-04-11 14:31 UTC, HansKristian-Work requested changes
Hard to review the logic without tests.

Could you add arithmetic tests as well to demonstrate the codegen?

`shaders-no-opt/comp/subgroups_basicvoteballot.vk.comp` and
`reference/shaders-no-opt/comp/subgroups_basicvoteballot.vk.comp` is a test for the existing emulation I think.

2023-04-11 15:09 UTC, HansKristian-Work commented
CI fails with a build error due to warning:

```
 /home/runner/work/SPIRV-Cross/SPIRV-Cross/spirv_glsl.cpp: In static member function ‘static bool spirv_cross::CompilerGLSL::is_supported_subgroup_op_in_opengl(spv::Op, const uint32_t*)’:
/home/runner/work/SPIRV-Cross/SPIRV-Cross/spirv_glsl.cpp:7354:3: error: this statement may fall through [-Werror=implicit-fallthrough=]
 7354 |   }
      |   ^
/home/runner/work/SPIRV-Cross/SPIRV-Cross/spirv_glsl.cpp:7356:2: note: here
 7356 |  default:
      |  ^~~~~~~
```

2023-05-10 09:24 UTC, HansKristian-Work approved these changes
Thanks for the tests, now it's more obvious what it's doing. Seems okay.

2023-05-10 09:27 UTC, georgeouzou commented
@HansKristian-Work  thanks, i will add the other operations too. (max, min, etc)

2023-05-10 09:32 UTC, merged

2023-05-10 09:32 UTC, HansKristian-Work commented
You can follow up in another PR with more opcodes.