Add support for the SPV_QCOM_image_processing extension
KhronosGroup/SPIRV-Cross pull request #2246
Opened 2023-12-12 22:51 UTC by wooyoungqcom

1. Add support for the SPV_QCOM_image_processing extension
2. Add four unit tests
3. Fix minor issues in other unit tests

Please note that 

the following test failed with "The flag --preserve-numeric-ids was specified multiple times."

shaders-no-opt/asm/frag/opaque-id-literal-alias.preserve.asm.frag

the following test failed with "The type of Value must match the Result type"

shaders-no-opt/asm/frag/subgroup-arithmetic-cast.nocompat.vk.asm.frag
shaders-msl-no-opt/asm/frag/subgroup-arithmetic-cast.msl21.asm.frag
  %18 = OpGroupNonUniformSMin %uint %uint_3 Reduce %16

the following tests failed with "Selection must be structured"

shaders-no-opt/asm/comp/loop-variable-early-read-with-initializer.asm.comp
  OpBranchConditional %69 %12 %13

shaders-no-opt/asm/comp/loop-variable-early-read-with-undef.asm.comp
  OpBranchConditional %69 %12 %13

the following tests failed with "OpSpecConstantComposite Constituent <id> '7[%7]'s type does not match Result Type <id> '29[%v3uint]'s vector element type."

shaders-no-opt/asm/comp/local-size-id.vk.asm.comp
shaders-hlsl-no-opt/asm/comp/local-size-id.asm.comp
shaders-msl-no-opt/asm/comp/local-size-id.asm.comp
  %38 = OpSpecConstantComposite %v3uint %37 %7 %uint_2

	
	shaders-msl-no-opt/asm/comp/local-size-id.asm.comp
	shaders-msl-no-opt/asm/frag/subgroup-arithmetic-cast.msl21.asm.frag

2024-01-05 12:40 UTC, HansKristian-Work commented
Rolling deps separately in https://github.com/KhronosGroup/SPIRV-Cross/pull/2254. You can rebase against that when it lands.

2024-01-06 06:43 UTC, wooyoungqcom commented
Rebased the branch.

2024-01-08 10:44 UTC, HansKristian-Work requested changes

2024-01-08 10:44 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +				expr = std::move("textureWeightedQCOM");
```suggestion
				expr = "textureWeightedQCOM";
```

2024-01-08 10:44 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +				expr = std::move("textureBoxFilterQCOM");
```suggestion
				expr = "textureBoxFilterQCOM";
```

2024-01-08 10:44 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +				expr = std::move("textureBlockMatchSSDQCOM");
```suggestion
				expr = "textureBlockMatchSSDQCOM";
```

2024-01-08 10:44 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +				expr = std::move("textureBlockMatchSADQCOM");
```suggestion
				expr = "textureBlockMatchSADQCOM";
```

2024-01-08 10:44 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +		if (opcode == OpImageBlockMatchSSDQCOM || opcode == OpImageBlockMatchSADQCOM )
```suggestion
		if (opcode == OpImageBlockMatchSSDQCOM || opcode == OpImageBlockMatchSADQCOM)
```

2024-01-08 10:44 UTC, HansKristian-Work commented on spirv_glsl.cpp
> +				SPIRV_CROSS_THROW("Invalid opcode for QCOM_image_processing.");
```suggestion
		case OpImageSampleWeightedQCOM:
			expr += ", " + to_non_uniform_aware_expression(ops[4]);
			break;
		case OpImageBoxFilterQCOM:
			expr += ", " + to_expression(ops[4]);
			break;
		case OpImageBlockMatchSSDQCOM:
		case OpImageBlockMatchSADQCOM:
			expr += ", " + to_non_uniform_aware_expression(ops[4]);
			expr += ", " + to_expression(ops[5]);
			expr += ", " + to_expression(ops[6]);
			break;
		default:
			SPIRV_CROSS_THROW("Invalid opcode for QCOM_image_processing.");
```

2024-01-08 18:00 UTC, wooyoungqcom commented
I have made the changes requested.

2024-01-09 15:40 UTC, merged